[package]
name = "rust_fib"
version = "0.1.0"
authors = ["Ysmr-Ry <ryo.yossy@live.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
